# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, timezone string must be offset from UTC (e.g. +01:00 or -01:00).
# Use this option on systems that have timezone support (most modern systems).
# If not specified, no timezone is taken into account when rendering dates.
# timezone =

# max length of characters to apply to the "slug" processing
# slug_length = 40

# set to 'true' to run the "environment" and "target" script
# during revision processing, regardless of whether a revision
# file is found.
# run_initial_revision = false

# set to 'true' to generate .pyc with .py file on revision apply
# sourceless = false

# version location specification; This defaults to alembic/versions.  When using
# version locations, if a "directoryRole" value is set, will be prepended to the
# path.  If a "url" is also supplied, this is prepended any file paths that are
# generated.  If not specified, the default is "versions" location.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator; If this separator is different from the most generic
# one, then file path separator will be replaced by this. On unix, a slash,
# on windows, backslash or dollar, depending on the platform.
# Typically, on unix, this should be "/", on Windows, it should be "$" or
# the default "/" is fine.  This option is only relevant for the version
# locations.
# version_path_separator = :

# the output encoding used when alembic generates new migration files.
# The default is "utf-8".
# output_encoding = utf-8

sqlalchemy.url = sqlite:///./data/beacon.db

[post_write_hooks]
# This is used by the "revision" and "shell" environment to control whether
# or not the various linters are run at the end of a command.
# The default is "false" (no hooks).
# hooks =

# hooks that can be executed if an error is raised... This is intended
# for the single autointegrate use-case and is very experimental!
# Hooks will respect any change made to the "template" environment variable
# The "autointegrate" hook, when enabled, will run all post-write hooks
# instead of just the ones generated by the most recent revision.
# autointegrate = false

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s %(message)s
datefmt = %H:%M:%S